### ISSUE TITLE
Wario

### ISSUE THREAD

**Issue by Just-Invincible** [CrowbertGame/bugs#1]
**Describe the bug**
There is wario

**To Reproduce**
Wario

**Expected behavior**
wario
**Screenshots**
![image](https://github.com/CrowbertGame/Bugs-Suggestions/assets/134889408/3b8f033f-70fe-4181-8675-99a7c6d47adf)

**Desktop (please complete the following information):**
 - OS: [wario ware]
 - Browser [Wario engine]
 - Version [Wario.5]

**Smartphone (please complete the following information):**
 - Device: [Wario phone 9]
 - OS: [Wario ware moble]
 - Browser [Wario engine]
 - Version [Wario.5]

**Additional context**
Why is wario

**Comment by badgeminer** [comment]
Wario
