### ISSUE TITLE
Why is wario chasing me

### ISSUE THREAD

**Issue by Just-Invincible** [CrowbertGame/bugs#2]
**Describe the bug**
He escaped

**To Reproduce**
HELP ME

**Expected behavior**
I expected to be playing my favorate game warioland
**Screenshots**
![image](https://github.com/CrowbertGame/Bugs-Suggestions/assets/134889408/c3841006-1763-45be-bb8f-0b0ddadfd41c)
![image](https://github.com/CrowbertGame/Bugs-Suggestions/assets/134889408/3268569b-c169-486a-8999-bbb14bb63481)
![image](https://github.com/CrowbertGame/Bugs-Suggestions/assets/134889408/5572ff57-c4fa-48e0-9ac5-bec99d7506b7)
![image](https://github.com/CrowbertGame/Bugs-Suggestions/assets/134889408/3d558ed5-ca54-4597-9e31-7e3a24dd935c)
![image](https://github.com/CrowbertGame/Bugs-Suggestions/assets/134889408/ebac203a-602b-4151-b673-efce0756c01b)

**Desktop (please complete the following information):**
 - OS: [Wario Ware 18]
**Additional context**
Hes gonan kill me

**Comment by badgeminer** [comment]
wario
